export const ROUTES = {
  HOME: "/",
  ADMIN_REGISTER: "/auth/admin/register",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  ADMIN: "/admin",
  ADMIN_SETUP: "/admin/setup",
  ADMIN_PREFERENCES: "/admin/preferences",
  ADMIN_QR: "/admin/qr",
  ADMIN_PLANS: "/admin/plans",
  ADMIN_MEMBERS: "/admin/members",
  ADMIN_TRAINERS: "/admin/trainers",
  ADMIN_ATTENDANCE: "/admin/attendance",
  ADMIN_EXPORTS: "/admin/exports",
  ADMIN_AUDIT: "/admin/audit",
  MEMBER: "/member",
  MEMBER_SCAN: "/member/scan",
  TRAINER: "/trainer",
} as const;
